apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-auth
spec:
  replicas: 2 # Alta disponibilidade para seu SaaS
  selector:
    matchLabels:
      app: sistema-auth
  template:
    metadata:
      labels:
        app: sistema-auth
    spec:
      containers:
        - name: sistema-auth
          image: pinheiromarllon/auth-service:46b0403be04af1b45e00a06e46bbf4f79ca6de55
          ports:
            - containerPort: 8080 # Porta padr√£o Spring Boot que vimos no Dockerfile
          envFrom:
            - configMapRef:
                name: sistema-auth-configmap